name: Build & push GHCR image with baked index

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug repo context
        run: |
          echo "--- DEBUG: repo root ---"
          pwd
          echo "--- ls -la ---"
          ls -la
          echo "--- show manage.py (first 120 lines) ---"
          if [ -f manage.py ]; then sed -n '1,120p' manage.py || true; else echo "(manage.py not found at repo root)"; fi
          echo "--- python info ---"
          python --version || true
          which python || true

      - name: Build index (CI)
        env:
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Running manage.py build in CI to produce index artifacts"
          python manage.py build

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./deploy/Dockerfile
          push: true
          tags: ghcr.io/belquer/oraculai:latest
          build-args: |
            PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }}
            PINECONE_ENVIRONMENT=${{ secrets.PINECONE_ENVIRONMENT }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
