name: Build & push GHCR image with baked index

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deploy/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/belquer/oraculai:latest
          secrets: |
            PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }}
            PINECONE_ENVIRONMENT=${{ secrets.PINECONE_ENVIRONMENT }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
