name: CI / Build and Publish

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/oraculai:latest
            ghcr.io/${{ github.repository_owner }}/oraculai:${{ github.ref == 'refs/heads/main' && 'main' || 'staging' }}
          file: ./Dockerfile

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    steps:
      - name: Deploy to Render (manual step)
        run: echo "Add your deployment step here or configure Render to auto-deploy from the staging branch"

  deploy-render:
    name: Deploy to Render
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          if [ -z "$RENDER_API_KEY" ] || [ -z "$RENDER_SERVICE_ID" ]; then
            echo "Render API Key or Service ID not set. Skipping deployment."
            exit 0
          fi
          set -euo pipefail
          echo "Triggering Render deploy for service $RENDER_SERVICE_ID"
          # Request a new deploy
          resp=$(curl -s -X POST \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -d '{"serviceId":"'$RENDER_SERVICE_ID'"}' \
            https://api.render.com/deploys)
          echo "Render deploy response: $resp"
          # Try to fetch service details (domain) for convenience
          svc=$(curl -s -X GET \
            -H "Accept: application/json" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            https://api.render.com/services/$RENDER_SERVICE_ID || true)
          echo "Render service info: $svc"
